# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_netif/test_apps/test_app_esp_netif:
  disable:
    - if: IDF_TARGET == "esp32c6"
      temporary: true
      reason: target esp32c6 is not supported yet
  disable_test:
    - if: IDF_TARGET != "esp32s2"
      temporary: true
      reason: lack of runners

components/esp_netif/test_apps/test_app_vfs_l2tap:
  disable:
    - if: SOC_EMAC_SUPPORTED != 1
      temporary: false
      reason: test uses internal EMAC
